sudo: required
services:
  - docker

before_install:
  - docker build -t udeshyagiri/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true udeshyagiri/react-test npm run test

after_success:
  - docker build -t udeshyagiri/fibo-client ./client
  - docker build -t udeshyagiri/fibo-nginx ./nginx
  - docker build -t udeshyagiri/fibo-server ./server
  - docker build -t udeshyagiri/fibo-worker ./worker
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push udeshyagiri/fibo-client
  - docker push udeshyagiri/fibo-nginx
  - docker push udeshyagiri/fibo-server
  - docker push udeshyagiri/fibo-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: fibo-docker
  env: Fibodocker-env
  bucket_name: elasticbeanstalk-us-east-1-054231087266
  bucket_path: fibo-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
